---
- name: Update servers
  hosts: alpine
  remote_user: root

  
  tasks:
  - name: Create a prometheus container
    docker_container:
      name: prometheus
      image: prom/prometheus:latest
      state: started
      restart: yes
      env:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      ports:
        - "9090:9090"
      volumes:
        - prometheus-conf:/etc/prometheus
        - prometheus-data:/prometheus

  - name: Create a portainer container
    docker_container:
      name: portainer
      image: cr.portainer.io/portainer/portainer-ce:latest
      state: started
      restart: yes
      env:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      ports:
        - "8000:8000"
        - "9000:9000"
        - "9443:9443"                
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data        