---
- name: Update servers
  hosts: alpine
  remote_user: root

  tasks:
  
  - name: pip
    apk:
      name: py3-pip
      update_cache: true

  - name: docker
    apk:
      name: docker
      update_cache: true

  - name: rsync
    apk:
      name: rsync
      update_cache: true

  - name: tailscale
    apk:
      name: tailscale
      update_cache: true

  - name: nano
    apk:
      name: nano
      update_cache: true                  
      
  - name: sshpass
    apk:
      name: sshpass
      update_cache: true  

  - name: Start tailscale service
    ansible.builtin.service:
      name: tailscale
      enabled: yes
      state: started    

  - name: Install python setuptools module
    pip:
      name: "setuptools" 

  # - name: Install python virtualenv module
  #   pip:
  #     name: "virtualenv"     

  - name: Install python request module
    pip:
      name: "requests"         