---
- name: Update web servers
  hosts: webservers
  remote_user: root

  tasks:
  # Update repositories and install "foo" package
  - apk:
      name: docker
      update_cache: yes
      update_cache: true