---
- name: Update servers
  hosts: 192.168.2.156
  remote_user: root

  tasks:
  # Update repositories and install "foo" package
  - apk:
      name: docker
      update_cache: yes
      update_cache: true